 **Fertilizer Recommendation system - NPK value Prediction**

In [16]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

In [17]:
data=pd.read_csv('/content/drive/MyDrive/agriculture dataset/Crop_recommendation.csv')
data.head()


N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [18]:
dataMapping= {
      "apple":1,
      "banana":2,
      "blackgram":3,
      "chickpea":4,
      "coconut":5,
      "coffee":6,
      "cotton":7,
      "grapes":8,
      "jute":9,
      "kidneybeans":10,
      "lentil":11,
      "maize":12,
      "mango":13,
      "mothbeans":14,
      "mungbean":15,
      "muskmelon":16,
      "orange":17,
      "papaya":18 ,
      "pigeonpeas":19,
      "pomegranate":20,
      "rice":21,
      "watermelon":22
}

In [19]:
data['label']=data['label'].map(dataMapping)
data

N   P   K  temperature   humidity        ph    rainfall  label
0      90  42  43    20.879744  82.002744  6.502985  202.935536     21
1      85  58  41    21.770462  80.319644  7.038096  226.655537     21
2      60  55  44    23.004459  82.320763  7.840207  263.964248     21
3      74  35  40    26.491096  80.158363  6.980401  242.864034     21
4      78  42  42    20.130175  81.604873  7.628473  262.717340     21
...   ...  ..  ..          ...        ...       ...         ...    ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507      6
2196   99  15  27    27.417112  56.636362  6.086922  127.924610      6
2197  118  33  30    24.131797  67.225123  6.362608  173.322839      6
2198  117  32  34    26.272418  52.127394  6.758793  127.175293      6
2199  104  18  30    23.603016  60.396475  6.779833  140.937041      6

[2200 rows x 8 columns]

In [20]:
npk_features = data.iloc[:,3:8].values
npk_labels = data.iloc[:, 0:3].values
print(npk_features)

[[ 20.87974371  82.00274423   6.50298529 202.9355362   21.        ]
 [ 21.77046169  80.31964408   7.03809636 226.6555374   21.        ]
 [ 23.00445915  82.3207629    7.84020714 263.9642476   21.        ]
 ...
 [ 24.13179691  67.22512329   6.36260785 173.3228386    6.        ]
 [ 26.2724184   52.12739421   6.75879255 127.1752928    6.        ]
 [ 23.60301571  60.39647474   6.77983261 140.9370415    6.        ]]


In [21]:
from sklearn.model_selection import train_test_split
ratio_train = 0.8
ratio_val = 0.1
ratio_test = 0.1
npk_x_remaining, npk_x_test, npk_y_remaining, npk_y_test = train_test_split(npk_features, npk_labels, test_size=ratio_test,random_state=10)
ratio_remaining = 1 - ratio_test
ratio_val_adjusted = ratio_val / ratio_remaining
npk_x_train, npk_x_val, npk_y_train, npk_y_val = train_test_split(npk_x_remaining, npk_y_remaining, test_size=ratio_val_adjusted,random_state=10)
print(npk_x_train)

[[ 25.6217169   66.50415474   6.04790668 105.4654703   12.        ]
 [ 25.9490364   94.73860514   6.47046561 144.1571109    5.        ]
 [ 26.27274407  62.28814857   7.41865067  70.23207557   3.        ]
 ...
 [ 29.3159075   80.11585705   5.92682475  90.10978128   2.        ]
 [ 24.18471151  69.94807345   7.04554306 163.2708732    6.        ]
 [ 29.47741671  91.57802915   7.12913694 111.1727497   17.        ]]


In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
npk_x_train = scaler.fit_transform(npk_x_train)
npk_x_test = scaler.fit_transform(npk_x_test)
npk_x_val = scaler.fit_transform(npk_x_val)
print(npk_x_train)

[[ 3.14654391e-03 -2.32904050e-01 -5.40266119e-01  4.22578353e-02
   8.05980616e-02]
 [ 6.84556779e-02  1.04729426e+00  1.25468424e-03  7.54740589e-01
  -1.01598087e+00]
 [ 1.33044154e-01 -4.24064987e-01  1.21637970e+00 -6.06543449e-01
  -1.32928914e+00]
 ...
 [ 7.40237945e-01  3.84273833e-01 -6.95435909e-01 -2.40507729e-01
  -1.48594327e+00]
 [-2.83575077e-01 -7.67508806e-02  7.38232115e-01  1.10670876e+00
  -8.59326737e-01]
 [ 7.72463420e-01  9.03988337e-01  8.45359959e-01  1.47353874e-01
   8.63868727e-01]]


In [23]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.multioutput import MultiOutputClassifier
knn=KNeighborsClassifier(n_neighbors=3)
multi_target = MultiOutputClassifier(knn)
multi_target.fit(npk_x_train,npk_y_train)

MultiOutputClassifier(estimator=KNeighborsClassifier(n_neighbors=3))

In [24]:
npk_predictions = multi_target.predict(npk_x_test)
npk_predictions

array([[ 25,  73,  76],
       [  3,   6,  33],
       [ 40,  40,  17],
       [ 82,  24,  30],
       [  1,   6,  35],
       [ 10,  65,  16],
       [ 82,  15,  48],
       [ 14,  18,  26],
       [  0,   6,  25],
       [  3,  43,  17],
       [ 60,  58,  19],
       [ 60,  44,  16],
       [ 62,  36,  20],
       [ 25,  62,  17],
       [ 86,  79,  45],
       [105,  36,  15],
       [ 20,  56,  77],
       [114,  40,  16],
       [ 43,  47,  47],
       [118,  45,  19],
       [ 21,  60,  16],
       [ 16,  60,  20],
       [ 14,  41,  15],
       [108,  36,  17],
       [ 13,  57,  18],
       [ 15,  25,  27],
       [ 18,  58,  16],
       [ 18,   7,   8],
       [ 22,  17,   5],
       [ 26,  52,  22],
       [ 60,  44,  15],
       [ 12,  30,  35],
       [103,  33,  25],
       [ 63,  36,  17],
       [108,  35,  17],
       [ 16,  51,  17],
       [ 83,  10,  51],
       [  4,  69,  18],
       [ 13,  40,  16],
       [  7, 139, 199],
       [ 83,  25,  49],
       [ 82,  29

In [25]:
print(npk_y_test)

[[ 49  69  82]
 [ 37  10  32]
 [122  48  16]
 [ 97  35  26]
 [ 31  29  35]
 [ 15  77  20]
 [108  26  52]
 [ 38  15  30]
 [ 31  20  26]
 [ 22  51  16]
 [ 87  60  23]
 [ 86  36  24]
 [ 74  39  23]
 [ 21  63  22]
 [ 83  94  47]
 [131  49  22]
 [ 35  57  83]
 [130  59  19]
 [ 70  54  46]
 [134  52  18]
 [ 58  61  15]
 [ 27  56  20]
 [  0  49  18]
 [134  56  18]
 [ 25  76  24]
 [ 12  19  31]
 [  5  56  24]
 [ 32  18  13]
 [  4   6   7]
 [ 76  39  24]
 [ 70  44  19]
 [ 22  23  44]
 [104  35  28]
 [ 96  46  22]
 [126  46  25]
 [  4  46  15]
 [ 84  25  52]
 [ 20  67  19]
 [111  53  19]
 [ 21 135 198]
 [117  25  53]
 [111  29  31]
 [ 39 132 196]
 [  5  25   6]
 [  5  65  16]
 [ 20   7  45]
 [ 39 145 201]
 [101  70  48]
 [ 69  46  41]
 [ 93  47  37]
 [ 31   6  26]
 [ 60  55  45]
 [ 67  55  44]
 [117  37  32]
 [ 29  76  15]
 [ 98   7  45]
 [ 56  75  15]
 [ 49  72  15]
 [ 93  53  38]
 [ 16  18  26]
 [ 17  74  17]
 [113  41  20]
 [ 74  39  38]
 [ 52  70  16]
 [111  28  26]
 [101  25  52]
 [ 52  73 

In [26]:
npk_input = [[20., 82., 6., 202.,21.]]
npk_input = scaler.fit_transform(npk_input)

npk_output= multi_target.predict(npk_input)
npk_output


array([[65, 44, 16]])

**Fertilizer recommendation from predicted npk value**

In [27]:
data=pd.read_csv('/content/drive/MyDrive/agriculture dataset/fertilizer.csv',encoding='windows-1254')
data.head()

Nitrogen (n)  Phosphorus (p)  Potassium (k)               Fertilizer
0           6.6             3.0            2.0          Cottonseed Meal
1           8.5             7.4            0.0      Ground Fish (Dried)
2           5.0             5.0            6.5  Fish, Blood & Bone meal
3           5.0             3.0            0.0  Activated Sewage Sludge
4          12.0             0.0            0.0               Blood Meal

In [28]:
fer_features = data.iloc[:,0:3].values
fer_labels = data.iloc[:,3].values
print(fer_features)

[[6.600e+00 3.000e+00 2.000e+00]
 [8.500e+00 7.400e+00 0.000e+00]
 [5.000e+00 5.000e+00 6.500e+00]
 [5.000e+00 3.000e+00 0.000e+00]
 [1.200e+01 0.000e+00 0.000e+00]
 [0.000e+00 3.500e+01 0.000e+00]
 [3.500e+00 1.700e+01 0.000e+00]
 [5.000e+00 2.000e+00 1.000e+00]
 [1.350e+00 1.000e+00 3.000e+00]
 [3.090e+00 2.500e+00 2.250e+00]
 [5.000e+00 2.000e+00 1.000e+00]
 [2.450e+00 5.000e-01 2.100e+00]
 [1.100e+01 2.000e+00 0.000e+00]
 [5.000e-02 2.000e-02 1.000e-01]
 [1.000e+00 1.500e-01 3.500e-01]
 [2.000e-01 2.000e-02 1.500e-01]
 [0.000e+00 3.080e+00 1.174e+01]
 [0.000e+00 1.800e+01 0.000e+00]
 [0.000e+00 0.000e+00 1.565e+01]
 [0.000e+00 3.250e+00 4.176e+01]
 [0.000e+00 2.340e+00 4.940e+01]
 [1.750e+00 7.500e-01 5.000e-01]
 [1.200e+01 1.600e+01 0.000e+00]
 [2.500e-01 1.000e-01 5.000e-01]
 [9.000e-01 5.000e-01 5.000e-02]
 [0.000e+00 0.000e+00 5.940e+00]
 [0.000e+00 3.470e+01 0.000e+00]
 [8.370e+00 1.140e+00 1.200e-01]
 [0.000e+00 9.770e+00 1.221e+01]
 [6.000e+00 2.500e+00 1.250e+00]
 [2.020e+0

In [29]:
from sklearn.model_selection import train_test_split
fer_x_train=fer_features
fer_y_train=fer_labels
fer_x_test=fer_features
fer_y_test=fer_labels

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
fer_x_train = scaler.fit_transform(fer_x_train)
fer_x_test = scaler.fit_transform(fer_x_test)
print(fer_x_train)

[[ 1.24069177e+00  1.51250270e-01 -1.91536757e-01]
 [ 1.80039947e+00  1.05294993e+00 -4.42465388e-01]
 [ 7.69358976e-01  5.61113750e-01  3.73052663e-01]
 [ 7.69358976e-01  1.51250270e-01 -4.42465388e-01]
 [ 2.83143997e+00 -4.63544950e-01 -4.42465388e-01]
 [-7.03556020e-01  6.70906595e+00 -4.42465388e-01]
 [ 3.27484477e-01  3.02029463e+00 -4.42465388e-01]
 [ 7.69358976e-01 -5.36814701e-02 -3.17001073e-01]
 [-3.05868971e-01 -2.58613210e-01 -6.60724415e-02]
 [ 2.06705447e-01  4.87843999e-02 -1.60170678e-01]
 [ 7.69358976e-01 -5.36814701e-02 -3.17001073e-01]
 [ 1.81723279e-02 -3.61079080e-01 -1.78990326e-01]
 [ 2.53685697e+00 -5.36814701e-02 -4.42465388e-01]
 [-6.88826870e-01 -4.59446315e-01 -4.29918957e-01]
 [-4.08973021e-01 -4.32805189e-01 -3.98552878e-01]
 [-6.44639420e-01 -4.59446315e-01 -4.23645741e-01]
 [-7.03556020e-01  1.67644809e-01  1.03048568e+00]
 [-7.03556020e-01  3.22522637e+00 -4.42465388e-01]
 [-7.03556020e-01 -4.63544950e-01  1.52105115e+00]
 [-7.03556020e-01  2.02483205e-

In [31]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(fer_x_train, fer_y_train)

KNeighborsClassifier(n_neighbors=1)

In [32]:
predictions = knn.predict(fer_x_test)
predictions

array(['Cottonseed Meal', 'Ground Fish (Dried)',
       'Fish, Blood & Bone meal', 'Activated Sewage Sludge',
       'Leather (Ground)', 'Rock Phosphate (Ground)', 'Bone Meal',
       'Poultry Litter (Dried)', 'Goat Manure (Dried)',
       'Sheep Manure (Dried)', 'Poultry Litter (Dried)', 'Alfalfa (Hay)',
       'Tankage', 'Apple (Fruit)', 'Apple (Leaves)', 'Apple (Pomace)',
       'Apple (Skin, Ash)', 'Basic Slag', 'Cana Tree (Ash)',
       'Banana Skin (Ash)', 'Banana Stalk (Ash)', 'Barley (Grain)',
       'Bat Guano', 'Sweetpotato', 'Brewery Grain (Wet)',
       'Brigham Tea (Ash)', 'Bone (Ground, Ash)',
       'Silk Mill (By products)', 'Cantaloupe skin (Melon) (Ash)',
       'Castor-Bean (Pomace)', 'Cattail / Bulrush reed & Stem',
       'Cattail / Bulrush Seed', 'Coal (Anthracite) (Ash)',
       'Coal (Bituminous) (Ash)', 'Cocoa shell (Dust)', 'Coffee Grounds',
       'Coffee Grounds (Dried)', 'Corncobs (Ground Charred)',
       'Common Crab', 'Nettles (Stinging European)', 'Comf

In [33]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(fer_y_test,predictions))
print(classification_report(fer_y_test,predictions))

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
                                 precision    recall  f1-score   support

        Activated Sewage Sludge       1.00      1.00      1.00         1
                  Alfalfa (Hay)       1.00      1.00      1.00         1
                  Apple (Fruit)       1.00      1.00      1.00         1
                 Apple (Leaves)       1.00      1.00      1.00         1
                 Apple (Pomace)       1.00      1.00      1.00         1
              Apple (Skin, Ash)       1.00      1.00      1.00         1
              Banana Skin (Ash)       1.00      1.00      1.00         1
             Banana Stalk (Ash)       1.00      1.00      1.00         1
                 Barley (Grain)       1.00      1.00      1.00         1
                     Basic Slag       1.00      1.00      1.00         1
                      Bat Guano       1.00      1.00      1.00         1
   

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [34]:
fer_a=npk_output
print(fer_a)
fer_b=[[65,44,16]];
fer_input=list(np.array(fer_a) - np.array(fer_b))
fer_input = scaler.fit_transform(fer_input)
fer_output= knn.predict(fer_input)
fer_output

[[65 44 16]]


array(['Insect Frass'], dtype=object)